[versions]

kotlin = "2.3.0"
coroutines = "1.10.2"
kotlinSerialization = "1.9.0"

koin = "4.1.1"
koinCompose = "4.1.1"

compose = "1.9.3"
navigationCompose = "2.9.1"
lifecycleCompose = "2.8.0"

sonar = "7.2.2.6593"
kover = "0.9.4"

dokka = "2.1.0"

publish = "0.34.0"

changelog = "2.5.0"

version = "0.2.1"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Compose navigation
jetbrains-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
jetbrains-lifecycle-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinCompose" }



[plugins]
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compiler-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

sonar = { id = "org.sonarqube", version.ref = "sonar" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }

changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }

version = { id = "com.n-apos.version", version.ref = "version" }
