name: Bump Version

on:
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to checkout and extract version from'
        required: true
        type: string
    outputs:
      version:
        description: "The new version number"
        value: ${{ jobs.bump.outputs.version }}
      sha:
        description: "The new commit SHA after bumping the version"
        value: ${{ jobs.bump.outputs.sha }}

jobs:
  bump:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      sha: ${{ steps.commit_and_push.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          GITHUB_TOKEN: $GITHUB_TOKEN
          ref: ${{ inputs.ref }}
          fetch-depth: 0 # Required to push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        if: "!contains(github.ref, 'release/promote')"
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TYPE=${BRANCH_NAME#release/}
          
          # Convert to uppercase
          INCREMENT_TYPE=$(echo "$TYPE" | tr '[:lower:]' '[:upper:]')
          
          # Replace hyphens with underscores (e.g. SUFFIX-INCREMENT -> SUFFIX_INCREMENT)
          INCREMENT_TYPE=${INCREMENT_TYPE//-/_}
          
          echo "Applying increment type: $INCREMENT_TYPE"
          
          ./gradlew incrementVersion --type=$INCREMENT_TYPE

      - name: Promote version
        if: "contains(github.ref, 'release/promote')"
        run: |
          ./gradlew promoteVersion

      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(./gradlew printVersion -q | sed '1d')" >> $GITHUB_OUTPUT

      - name: Patch changelog
        run: ./gradlew patchChangelog

      - name: Re-generate readme
        run: ./gradlew generateReadme

      - name: Commit, Tag and Push
        id: commit_and_push
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add version.properties
          git add CHANGELOG.md
          git add README.md
          git commit -m "chore(bump_version): Bump version to ${{ steps.extract_version.outputs.version }}"
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          git tag "v${{ steps.extract_version.outputs.version }}"
          git push
          git push --tags
