name: Release and Publish

on:
  workflow_call:
    inputs:
      sha:
        description: 'The git SHA to check out'
        required: true
        type: string
      version:
        description: 'The version to release'
        required: true
        type: string
    secrets:
      GRADLE_SECRET_PROPERTIES:
        required: true
      GPG_SIGNING_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GRADLE_SECRET_PROPERTIES }}" >> gradle.properties
          printf "%s\n" "${{ secrets.GPG_SIGNING_KEY }}" | gpg --batch --import
          cat gradle.properties
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Test GPG Key signing
        run: |
          echo "Test" | gpg --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --sign
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish "core" to Maven Central
        run: ./gradlew :core:publishToMavenCentral --no-configuration-cache
        env:
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish "compose" to Maven Central
        run: ./gradlew :compose:publishToMavenCentral --no-configuration-cache
        env:
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}

  release:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
